"use client";

import { useState, useRef, useCallback } from "react";
import {
  Cable,
  Search,
  Filter,
  AlertTriangle,
  Info,
  Zap,
  ArrowRight,
  ArrowLeft,
  Camera,
  Loader2,
  X,
  ShieldCheck,
  CheckCircle2,
  XCircle,
} from "lucide-react";
import { useProject } from "@/lib/project-context";
import Link from "next/link";

const wireColorStyles: Record<string, string> = {
  red: "bg-red-500",
  black: "bg-gray-900 dark:bg-gray-200",
  blue: "bg-blue-500",
  yellow: "bg-yellow-400",
  green: "bg-green-500",
  white: "bg-white border border-gray-300",
  orange: "bg-orange-500",
  brown: "bg-amber-800",
  purple: "bg-purple-500",
  gray: "bg-gray-400",
};

export default function SchematicsPage() {
  const {
    connections,
    powerRails,
    designNotes,
    takeWiringPhoto,
    visionResult,
    visionLoading,
    clearVisionResult,
  } = useProject();

  const [search, setSearch] = useState("");
  const [signalFilter, setSignalFilter] = useState("all");
  const [showCamera, setShowCamera] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null);
  const streamRef = useRef<MediaStream | null>(null);

  const startCamera = useCallback(async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: "environment" },
      });
      streamRef.current = stream;
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
      }
      setShowCamera(true);
    } catch {
      alert("Could not access camera. Please check permissions.");
    }
  }, []);

  const stopCamera = useCallback(() => {
    if (streamRef.current) {
      streamRef.current.getTracks().forEach((t) => t.stop());
      streamRef.current = null;
    }
    setShowCamera(false);
  }, []);

  const captureAndSend = useCallback(async () => {
    if (!videoRef.current) return;
    const canvas = document.createElement("canvas");
    canvas.width = videoRef.current.videoWidth;
    canvas.height = videoRef.current.videoHeight;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    ctx.drawImage(videoRef.current, 0, 0);
    const base64 = canvas.toDataURL("image/jpeg", 0.8);
    stopCamera();
    await takeWiringPhoto(base64);
  }, [stopCamera, takeWiringPhoto]);

  const filtered = connections.filter((c) => {
    const matchSearch =
      c.from.part.toLowerCase().includes(search.toLowerCase()) ||
      c.to.part.toLowerCase().includes(search.toLowerCase()) ||
      c.signal.toLowerCase().includes(search.toLowerCase());

    if (signalFilter === "all") return matchSearch;
    if (signalFilter === "power")
      return (
        matchSearch &&
        (c.signal.toLowerCase().includes("power") ||
          c.signal.toLowerCase().includes("ground") ||
          c.signal.toLowerCase().includes("vcc") ||
          c.signal.toLowerCase().includes("gnd"))
      );
    return (
      matchSearch && c.signal.toLowerCase().includes(signalFilter.toLowerCase())
    );
  });

  const signalTypes = [
    "all",
    "power",
    ...Array.from(
      new Set(
        connections
          .map((c) => c.signal.split(" ")[0].toLowerCase())
          .filter(
            (s) =>
              s !== "power" &&
              s !== "ground" &&
              s !== "gnd" &&
              s !== "vcc" &&
              s !== "3v3" &&
              s !== "5v"
          )
      )
    ).slice(0, 4),
  ];

  if (connections.length === 0) {
    return (
      <div className="mx-auto max-w-3xl px-4 py-16 text-center">
        <Cable className="mx-auto h-16 w-16 text-muted/30" />
        <h1 className="mt-6 text-2xl font-bold">No Wiring Diagram Yet</h1>
        <p className="mt-2 text-muted max-w-md mx-auto">
          Wiring connections are generated by the AI after you describe your
          project. Ask the AI to generate a wiring diagram in the Project chat.
        </p>
        <Link
          href="/project"
          className="mt-6 inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-2.5 text-sm font-medium text-white hover:bg-primary/90 transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          Go to Project
        </Link>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      <div className="mb-6">
        <div className="flex items-center gap-2 text-sm text-muted mb-1">
          <Cable className="h-4 w-4" />
          Wiring Schematics
        </div>
        <h1 className="text-2xl font-bold sm:text-3xl">Wiring & Schematics</h1>
        <p className="mt-1 text-muted">
          Pin-to-pin wiring diagram generated by AI. Use the camera to verify
          your wiring.
        </p>
      </div>

      {/* Camera / Vision section */}
      <div className="mb-6 rounded-xl border border-border bg-background p-4 shadow-sm">
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-semibold flex items-center gap-2">
            <Camera className="h-4 w-4" />
            Wiring Verification
          </h3>
          {!showCamera && (
            <button
              onClick={startCamera}
              disabled={visionLoading}
              className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white hover:bg-primary/90 transition-colors disabled:opacity-50"
            >
              <Camera className="h-4 w-4" />
              Take Wiring Photo
            </button>
          )}
        </div>

        {showCamera && (
          <div className="relative rounded-lg overflow-hidden bg-black mb-3">
            <video
              ref={videoRef}
              autoPlay
              playsInline
              muted
              className="w-full max-h-[400px] object-contain"
            />
            <div className="absolute bottom-4 left-1/2 -translate-x-1/2 flex items-center gap-3">
              <button
                onClick={captureAndSend}
                className="flex items-center gap-2 rounded-full bg-primary px-6 py-2.5 text-sm font-medium text-white shadow-lg hover:bg-primary/90"
              >
                <Camera className="h-4 w-4" />
                Capture & Check
              </button>
              <button
                onClick={stopCamera}
                className="rounded-full bg-black/60 p-2.5 text-white backdrop-blur-sm hover:bg-black/80"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          </div>
        )}

        {visionLoading && (
          <div className="flex items-center gap-3 p-4 rounded-lg bg-primary/5 border border-primary/20">
            <Loader2 className="h-5 w-5 animate-spin text-primary" />
            <span className="text-sm text-primary">
              Analyzing your wiring photo...
            </span>
          </div>
        )}

        {visionResult && (
          <div className="space-y-3 mt-3">
            <div className="flex items-center justify-between">
              <h4 className="font-semibold text-sm">Analysis Result</h4>
              <button
                onClick={clearVisionResult}
                className="text-xs text-muted hover:text-foreground"
              >
                Dismiss
              </button>
            </div>
            <p className="text-sm text-muted">{visionResult.summary}</p>

            {visionResult.issues.length > 0 && (
              <div className="space-y-2">
                {visionResult.issues.map((issue, i) => (
                  <div
                    key={i}
                    className={`flex items-start gap-2 rounded-lg p-3 text-sm ${
                      issue.severity === "error"
                        ? "bg-danger/10 text-danger border border-danger/20"
                        : "bg-accent/10 text-accent border border-accent/20"
                    }`}
                  >
                    <AlertTriangle className="h-4 w-4 shrink-0 mt-0.5" />
                    {issue.description}
                  </div>
                ))}
              </div>
            )}

            {visionResult.checklist.length > 0 && (
              <div className="rounded-lg border border-border p-3">
                <h5 className="text-xs font-semibold text-muted mb-2">
                  VERIFICATION CHECKLIST
                </h5>
                <div className="space-y-1.5">
                  {visionResult.checklist.map((item, i) => (
                    <div key={i} className="flex items-center gap-2 text-sm">
                      {item.status === "ok" ? (
                        <CheckCircle2 className="h-4 w-4 text-success" />
                      ) : item.status === "issue" ? (
                        <XCircle className="h-4 w-4 text-danger" />
                      ) : (
                        <Info className="h-4 w-4 text-muted" />
                      )}
                      <span>{item.item}</span>
                      {item.note && (
                        <span className="text-xs text-muted">
                          — {item.note}
                        </span>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        <p className="mt-3 flex items-center gap-1.5 text-xs text-muted">
          <ShieldCheck className="h-3.5 w-3.5" />
          Photos are only sent when you tap &quot;Capture & Check&quot;. Frames
          are never auto-sent.
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Connection table */}
        <div className="lg:col-span-2 space-y-4">
          <div className="rounded-xl border border-border bg-background shadow-sm overflow-hidden">
            <div className="border-b border-border px-4 py-3 flex items-center justify-between">
              <h2 className="font-semibold">Connections ({filtered.length})</h2>
              <div className="relative">
                <Search className="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted" />
                <input
                  type="text"
                  placeholder="Search..."
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  className="rounded-md border border-border bg-surface pl-8 pr-3 py-1.5 text-xs outline-none focus:border-primary w-40"
                />
              </div>
            </div>

            {/* Signal filters */}
            <div className="border-b border-border px-4 py-2 flex items-center gap-2">
              <Filter className="h-3.5 w-3.5 text-muted" />
              {signalTypes.map((f) => (
                <button
                  key={f}
                  onClick={() => setSignalFilter(f)}
                  className={`rounded-md px-2.5 py-1 text-xs font-medium transition-colors ${
                    signalFilter === f
                      ? "bg-primary text-white"
                      : "text-muted hover:text-foreground"
                  }`}
                >
                  {f === "all" ? "All" : f.charAt(0).toUpperCase() + f.slice(1)}
                </button>
              ))}
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-border bg-surface text-xs text-muted">
                    <th className="px-4 py-2 text-left font-medium">Wire</th>
                    <th className="px-4 py-2 text-left font-medium">From</th>
                    <th className="px-4 py-2 text-center font-medium"></th>
                    <th className="px-4 py-2 text-left font-medium">To</th>
                    <th className="px-4 py-2 text-left font-medium">Signal</th>
                    <th className="px-4 py-2 text-left font-medium">Notes</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {filtered.map((conn) => (
                    <tr key={conn.id} className="hover:bg-surface/50">
                      <td className="px-4 py-2.5">
                        <div className="flex items-center gap-2">
                          <div
                            className={`h-3 w-3 rounded-full ${
                              conn.wireColor
                                ? wireColorStyles[conn.wireColor] ||
                                  "bg-gray-400"
                                : "bg-gray-400"
                            }`}
                          />
                          <span className="text-xs text-muted capitalize">
                            {conn.wireColor || "—"}
                          </span>
                        </div>
                      </td>
                      <td className="px-4 py-2.5">
                        <div className="font-medium text-xs">
                          {conn.from.part}
                        </div>
                        <div className="text-xs text-muted">
                          {conn.from.pin}
                        </div>
                      </td>
                      <td className="px-4 py-2.5 text-center">
                        <ArrowRight className="h-3.5 w-3.5 text-muted mx-auto" />
                      </td>
                      <td className="px-4 py-2.5">
                        <div className="font-medium text-xs">
                          {conn.to.part}
                        </div>
                        <div className="text-xs text-muted">{conn.to.pin}</div>
                      </td>
                      <td className="px-4 py-2.5">
                        <span className="inline-flex items-center rounded-md bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">
                          {conn.signal}
                        </span>
                      </td>
                      <td className="px-4 py-2.5 text-xs text-muted max-w-[150px] truncate">
                        {conn.notes || "—"}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* Sidebar */}
        <div className="space-y-4">
          {/* Power rails */}
          {powerRails.length > 0 && (
            <div className="rounded-xl border border-border bg-background p-5 shadow-sm">
              <h3 className="font-semibold mb-3 flex items-center gap-2">
                <Zap className="h-4 w-4 text-accent" />
                Power Rails
              </h3>
              <div className="space-y-4">
                {powerRails.map((rail, i) => (
                  <div key={i} className="rounded-lg border border-border p-3">
                    <div className="flex items-center justify-between mb-2">
                      <span className="font-bold text-sm">{rail.voltage}</span>
                      <span className="text-xs text-muted">{rail.source}</span>
                    </div>
                    <div className="space-y-1">
                      {rail.consumers.map((consumer, j) => (
                        <div
                          key={j}
                          className="flex items-center gap-1.5 text-xs text-muted"
                        >
                          <div className="h-1.5 w-1.5 rounded-full bg-success" />
                          {consumer}
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Design notes */}
          {designNotes.length > 0 && (
            <div className="rounded-xl border border-border bg-background p-5 shadow-sm">
              <h3 className="font-semibold mb-3 flex items-center gap-2">
                <Info className="h-4 w-4 text-secondary" />
                Design Notes
              </h3>
              <div className="space-y-2">
                {designNotes.map((note, i) => (
                  <div
                    key={i}
                    className="flex items-start gap-2 text-xs text-muted"
                  >
                    <Info className="h-3 w-3 shrink-0 mt-0.5 text-secondary" />
                    {note}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Warning */}
          <div className="rounded-xl border border-accent/30 bg-accent/5 p-4">
            <div className="flex items-start gap-2">
              <AlertTriangle className="h-4 w-4 shrink-0 mt-0.5 text-accent" />
              <div>
                <h4 className="text-sm font-semibold text-accent">
                  Before powering on
                </h4>
                <p className="text-xs text-accent/80 mt-1">
                  Double-check all connections against this diagram. Use the
                  camera to let AI verify your wiring before connecting power.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
