"use client";

import { useState } from "react";
import {
  Box,
  CheckCircle2,
  Circle,
  ChevronRight,
  AlertTriangle,
  Lightbulb,
  Package,
  ArrowLeft,
} from "lucide-react";
import { useProject } from "@/lib/project-context";
import Link from "next/link";

export default function AssemblyPage() {
  const { assemblySteps, bom, toggleStepComplete } = useProject();
  const [activeStep, setActiveStep] = useState<string | null>(() => {
    const first = assemblySteps.find((s) => !s.completed);
    return first?.id || assemblySteps[0]?.id || null;
  });

  const completedCount = assemblySteps.filter((s) => s.completed).length;
  const progress =
    assemblySteps.length > 0
      ? Math.round((completedCount / assemblySteps.length) * 100)
      : 0;

  const getPartName = (id: string) => {
    const part = bom.find((p) => p.id === id || p.name === id);
    return part?.name || id;
  };

  if (assemblySteps.length === 0) {
    return (
      <div className="mx-auto max-w-3xl px-4 py-16 text-center">
        <Box className="mx-auto h-16 w-16 text-muted/30" />
        <h1 className="mt-6 text-2xl font-bold">No Assembly Steps Yet</h1>
        <p className="mt-2 text-muted max-w-md mx-auto">
          Assembly instructions are generated by the AI after you describe your
          project and get a bill of materials. Head to the Project page and tell
          the AI what you&apos;re building.
        </p>
        <Link
          href="/project"
          className="mt-6 inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-2.5 text-sm font-medium text-white hover:bg-primary/90 transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          Go to Project
        </Link>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      <div className="mb-6">
        <div className="flex items-center gap-2 text-sm text-muted mb-1">
          <Box className="h-4 w-4" />
          Assembly Guide
        </div>
        <h1 className="text-2xl font-bold sm:text-3xl">Assembly</h1>
        <p className="mt-1 text-muted">
          Step-by-step assembly instructions generated by AI. Mark steps as
          complete as you go.
        </p>
      </div>

      {/* Progress */}
      <div className="mb-6 rounded-xl border border-border bg-background p-4 shadow-sm">
        <div className="flex items-center justify-between mb-2">
          <span className="text-sm font-medium">
            {completedCount} of {assemblySteps.length} steps completed
          </span>
          <span className="text-sm font-bold">{progress}%</span>
        </div>
        <div className="h-2.5 rounded-full bg-border">
          <div
            className="h-full rounded-full bg-success transition-all"
            style={{ width: `${progress}%` }}
          />
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Step list */}
        <div className="lg:col-span-1">
          <div className="rounded-xl border border-border bg-background shadow-sm overflow-hidden">
            <div className="border-b border-border px-4 py-3">
              <h2 className="font-semibold text-sm">Steps</h2>
            </div>
            <div className="divide-y divide-border max-h-[600px] overflow-y-auto">
              {assemblySteps.map((step) => {
                const isCurrent = step.id === activeStep;
                const currentStepIndex = assemblySteps.findIndex(
                  (s) => !s.completed
                );
                const isNext =
                  assemblySteps.indexOf(step) === currentStepIndex;

                return (
                  <button
                    key={step.id}
                    onClick={() => setActiveStep(step.id)}
                    className={`w-full px-4 py-3 text-left transition-colors ${
                      isCurrent ? "bg-primary/5" : "hover:bg-surface"
                    }`}
                  >
                    <div className="flex items-center gap-2.5">
                      {step.completed ? (
                        <CheckCircle2 className="h-4 w-4 shrink-0 text-success" />
                      ) : isNext ? (
                        <ChevronRight className="h-4 w-4 shrink-0 text-primary" />
                      ) : (
                        <Circle className="h-4 w-4 shrink-0 text-muted/30" />
                      )}
                      <div className="min-w-0">
                        <div
                          className={`text-sm font-medium truncate ${
                            step.completed ? "text-muted line-through" : ""
                          }`}
                        >
                          {step.order}. {step.title}
                        </div>
                      </div>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        {/* Active step detail */}
        <div className="lg:col-span-2">
          {activeStep ? (
            (() => {
              const step = assemblySteps.find((s) => s.id === activeStep);
              if (!step) return null;
              return (
                <div className="rounded-2xl border border-border bg-background shadow-sm overflow-hidden">
                  {/* Header */}
                  <div className="relative bg-gradient-to-br from-slate-900 to-slate-800 px-6 py-8">
                    <div className="text-white">
                      <div className="flex items-center gap-2 text-white/60 text-sm mb-2">
                        Step {step.order} of {assemblySteps.length}
                      </div>
                      <h2 className="text-xl font-bold">{step.title}</h2>
                    </div>
                    {step.completed && (
                      <div className="absolute top-4 right-4 flex items-center gap-1.5 rounded-full bg-success/90 px-3 py-1 text-xs font-medium text-white backdrop-blur-sm">
                        <CheckCircle2 className="h-3.5 w-3.5" />
                        Completed
                      </div>
                    )}
                  </div>

                  {/* Step details */}
                  <div className="p-6">
                    <p className="text-muted leading-relaxed">
                      {step.description}
                    </p>

                    {/* Parts used */}
                    {step.partsUsed.length > 0 && (
                      <div className="mt-4">
                        <h3 className="text-sm font-semibold text-muted mb-2">
                          PARTS NEEDED
                        </h3>
                        <div className="flex flex-wrap gap-2">
                          {step.partsUsed.map((pId) => (
                            <span
                              key={pId}
                              className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-surface px-3 py-1.5 text-xs font-medium"
                            >
                              <Package className="h-3 w-3 text-primary" />
                              {getPartName(pId)}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Warning */}
                    {step.warnings && (
                      <div className="mt-4 flex items-start gap-2.5 rounded-lg border border-accent/30 bg-accent/5 p-4">
                        <AlertTriangle className="h-5 w-5 shrink-0 text-accent mt-0.5" />
                        <div>
                          <h4 className="text-sm font-semibold text-accent">
                            Safety Warning
                          </h4>
                          <p className="text-sm text-accent/80 mt-0.5">
                            {step.warnings}
                          </p>
                        </div>
                      </div>
                    )}

                    {/* Tips */}
                    {step.tips && (
                      <div className="mt-4 flex items-start gap-2.5 rounded-lg border border-primary/20 bg-primary/5 p-4">
                        <Lightbulb className="h-5 w-5 shrink-0 text-primary mt-0.5" />
                        <div>
                          <h4 className="text-sm font-semibold text-primary">
                            AI Tip
                          </h4>
                          <p className="text-sm text-primary/80 mt-0.5">
                            {step.tips}
                          </p>
                        </div>
                      </div>
                    )}

                    {/* Complete button */}
                    <button
                      onClick={() => toggleStepComplete(step.id)}
                      className={`mt-6 flex items-center gap-2 rounded-lg px-5 py-2.5 text-sm font-medium transition-colors ${
                        step.completed
                          ? "bg-surface text-muted hover:bg-danger/10 hover:text-danger border border-border"
                          : "bg-success text-white hover:bg-success/90"
                      }`}
                    >
                      {step.completed ? (
                        <>
                          <CheckCircle2 className="h-4 w-4" />
                          Mark Incomplete
                        </>
                      ) : (
                        <>
                          <Circle className="h-4 w-4" />
                          Mark Complete
                        </>
                      )}
                    </button>
                  </div>
                </div>
              );
            })()
          ) : (
            <div className="flex h-64 items-center justify-center rounded-2xl border border-border bg-background text-muted">
              Select a step to view details
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
