"use client";

import { useState } from "react";
import {
  Code,
  FileCode,
  Copy,
  Check,
  Package,
  ChevronDown,
  ChevronRight,
  ArrowLeft,
} from "lucide-react";
import { useProject, type CodeSnippet } from "@/lib/project-context";
import Link from "next/link";

function FirmwareCard({ snippet }: { snippet: CodeSnippet }) {
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(snippet.code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="rounded-xl border border-border bg-background shadow-sm overflow-hidden">
      {/* Header */}
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full px-5 py-4 text-left hover:bg-surface/50 transition-colors"
      >
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
              <FileCode className="h-5 w-5 text-primary" />
            </div>
            <div>
              <h3 className="font-semibold">{snippet.name}</h3>
              <p className="text-xs text-muted mt-0.5">
                {snippet.filename} &middot; {snippet.language}
              </p>
            </div>
          </div>
          {expanded ? (
            <ChevronDown className="h-4 w-4 text-muted mt-1" />
          ) : (
            <ChevronRight className="h-4 w-4 text-muted mt-1" />
          )}
        </div>
        <p className="mt-2 text-sm text-muted">{snippet.description}</p>
      </button>

      {expanded && (
        <div className="border-t border-border">
          {/* Dependencies */}
          {snippet.dependencies.length > 0 && (
            <div className="px-5 py-3 border-b border-border bg-surface/50">
              <h4 className="text-xs font-semibold text-muted mb-2">
                DEPENDENCIES
              </h4>
              <div className="flex flex-wrap gap-1.5">
                {snippet.dependencies.map((dep) => (
                  <span
                    key={dep}
                    className="inline-flex items-center gap-1 rounded-md border border-border bg-background px-2 py-0.5 text-xs font-mono"
                  >
                    <Package className="h-3 w-3 text-muted" />
                    {dep}
                  </span>
                ))}
              </div>
              {snippet.installInstructions && (
                <p className="mt-2 text-xs text-muted font-mono">
                  {snippet.installInstructions}
                </p>
              )}
            </div>
          )}

          {/* Code */}
          <div className="relative">
            <div className="absolute top-2 right-2 z-10">
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 rounded-md bg-background/80 border border-border px-2.5 py-1.5 text-xs font-medium backdrop-blur-sm transition-colors hover:bg-surface"
              >
                {copied ? (
                  <>
                    <Check className="h-3 w-3 text-success" />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy className="h-3 w-3" />
                    Copy
                  </>
                )}
              </button>
            </div>
            <pre className="overflow-x-auto bg-slate-950 p-5 text-xs leading-relaxed text-slate-300 max-h-[500px]">
              <code>{snippet.code}</code>
            </pre>
          </div>
        </div>
      )}
    </div>
  );
}

export default function FirmwarePage() {
  const { codeSnippets } = useProject();
  const allDeps = Array.from(
    new Set(codeSnippets.flatMap((s) => s.dependencies))
  ).sort();

  if (codeSnippets.length === 0) {
    return (
      <div className="mx-auto max-w-3xl px-4 py-16 text-center">
        <Code className="mx-auto h-16 w-16 text-muted/30" />
        <h1 className="mt-6 text-2xl font-bold">No Firmware Yet</h1>
        <p className="mt-2 text-muted max-w-md mx-auto">
          Code snippets and firmware modules are generated by the AI once you
          have a bill of materials and wiring diagram. Ask the AI to generate
          firmware in the Project chat.
        </p>
        <Link
          href="/project"
          className="mt-6 inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-2.5 text-sm font-medium text-white hover:bg-primary/90 transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          Go to Project
        </Link>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      <div className="mb-6">
        <div className="flex items-center gap-2 text-sm text-muted mb-1">
          <Code className="h-4 w-4" />
          Firmware Development
        </div>
        <h1 className="text-2xl font-bold sm:text-3xl">Firmware</h1>
        <p className="mt-1 text-muted">
          AI-generated code for your project. Review, copy, and flash to your
          microcontroller.
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Firmware modules */}
        <div className="lg:col-span-2 space-y-4">
          {codeSnippets.map((snippet) => (
            <FirmwareCard key={snippet.id} snippet={snippet} />
          ))}
        </div>

        {/* Sidebar */}
        <div className="space-y-4">
          {/* All dependencies */}
          {allDeps.length > 0 && (
            <div className="rounded-xl border border-border bg-background p-5 shadow-sm">
              <h3 className="font-semibold mb-3">All Libraries</h3>
              <div className="space-y-1.5">
                {allDeps.map((dep) => (
                  <div
                    key={dep}
                    className="flex items-center gap-2 text-sm text-muted"
                  >
                    <Package className="h-3.5 w-3.5 shrink-0" />
                    <span className="font-mono text-xs">{dep}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Quick instructions */}
          <div className="rounded-xl border border-primary/30 bg-primary/5 p-4">
            <h4 className="text-sm font-semibold text-primary mb-2">
              How to Use
            </h4>
            <ol className="space-y-1.5 text-xs text-primary/80">
              <li>1. Install required libraries listed above</li>
              <li>2. Copy each code file to your project</li>
              <li>3. Update pin definitions to match your wiring</li>
              <li>4. Connect your board via USB</li>
              <li>5. Compile and upload</li>
            </ol>
          </div>

          {/* Module count */}
          <div className="rounded-xl border border-border bg-background p-5 shadow-sm">
            <h3 className="font-semibold mb-3">Summary</h3>
            <div className="space-y-2 text-sm">
              <div className="flex items-center justify-between">
                <span className="text-muted">Code files</span>
                <span className="font-bold">{codeSnippets.length}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-muted">Libraries needed</span>
                <span className="font-bold">{allDeps.length}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
